# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AboutWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AboutWidget(object):
    def setupUi(self, AboutWidget):
        AboutWidget.setObjectName("AboutWidget")
        AboutWidget.resize(434, 284)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("App/resources/icons/info_black.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        AboutWidget.setWindowIcon(icon)
        AboutWidget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.logo = QtWidgets.QLabel(AboutWidget)
        self.logo.setGeometry(QtCore.QRect(20, 20, 100, 100))
        self.logo.setPixmap(QtGui.QPixmap("App/resources/icons/logo.svg"))
        self.logo.setScaledContents(True)
        self.logo.setObjectName("logo")
        self.title_label = QtWidgets.QLabel(AboutWidget)
        self.title_label.setGeometry(QtCore.QRect(140, 30, 121, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.title_label.sizePolicy().hasHeightForWidth())
        self.title_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.title_label.setFont(font)
        self.title_label.setObjectName("title_label")
        self.copyright_label = QtWidgets.QLabel(AboutWidget)
        self.copyright_label.setGeometry(QtCore.QRect(140, 90, 211, 16))
        self.copyright_label.setObjectName("copyright_label")
        self.description_label = QtWidgets.QLabel(AboutWidget)
        self.description_label.setGeometry(QtCore.QRect(140, 70, 91, 16))
        self.description_label.setObjectName("description_label")
        self.version_title_label = QtWidgets.QLabel(AboutWidget)
        self.version_title_label.setGeometry(QtCore.QRect(30, 150, 71, 16))
        self.version_title_label.setObjectName("version_title_label")
        self.lib_label = QtWidgets.QLabel(AboutWidget)
        self.lib_label.setGeometry(QtCore.QRect(30, 190, 71, 16))
        self.lib_label.setObjectName("lib_label")
        self.pyqt5_label = QtWidgets.QLabel(AboutWidget)
        self.pyqt5_label.setGeometry(QtCore.QRect(120, 190, 55, 16))
        self.pyqt5_label.setObjectName("pyqt5_label")
        self.pillow_label = QtWidgets.QLabel(AboutWidget)
        self.pillow_label.setGeometry(QtCore.QRect(120, 210, 55, 16))
        self.pillow_label.setObjectName("pillow_label")
        self.tinytag_label = QtWidgets.QLabel(AboutWidget)
        self.tinytag_label.setGeometry(QtCore.QRect(120, 230, 55, 16))
        self.tinytag_label.setObjectName("tinytag_label")
        self.github_button = QtWidgets.QPushButton(AboutWidget)
        self.github_button.setGeometry(QtCore.QRect(220, 210, 181, 28))
        self.github_button.setStyleSheet("QPushButton{\n"
"background-color: #6240C2;\n"
"border-radius: 10px;\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"   background-color:#4422A4;\n"
"}")
        self.github_button.setObjectName("github_button")
        self.version_label = QtWidgets.QLabel(AboutWidget)
        self.version_label.setGeometry(QtCore.QRect(120, 150, 51, 16))
        self.version_label.setText("")
        self.version_label.setObjectName("version_label")
        self.developer_label = QtWidgets.QLabel(AboutWidget)
        self.developer_label.setGeometry(QtCore.QRect(220, 150, 171, 16))
        self.developer_label.setObjectName("developer_label")
        self.designer_label = QtWidgets.QLabel(AboutWidget)
        self.designer_label.setGeometry(QtCore.QRect(220, 170, 171, 16))
        self.designer_label.setObjectName("designer_label")

        #
        AboutWidget.setFixedSize(435, 285)
        #

        self.retranslateUi(AboutWidget)
        QtCore.QMetaObject.connectSlotsByName(AboutWidget)

    def retranslateUi(self, AboutWidget):
        _translate = QtCore.QCoreApplication.translate
        AboutWidget.setWindowTitle(_translate("AboutWidget", "About"))
        self.title_label.setText(_translate("AboutWidget", "Shuffle"))
        self.copyright_label.setText(_translate("AboutWidget", "Copyright (c) 2022 Renat Skosarev"))
        self.description_label.setText(_translate("AboutWidget", "Audio Player"))
        self.version_title_label.setText(_translate("AboutWidget", "Version:"))
        self.lib_label.setText(_translate("AboutWidget", "Libraries:"))
        self.pyqt5_label.setText(_translate("AboutWidget", "• PyQt5"))
        self.pillow_label.setText(_translate("AboutWidget", "• Pillow"))
        self.tinytag_label.setText(_translate("AboutWidget", "• tinytag"))
        self.github_button.setText(_translate("AboutWidget", "GitHub"))
        self.developer_label.setText(_translate("AboutWidget", "Developed by Renat Skosarev"))
        self.designer_label.setText(_translate("AboutWidget", "Designed by Eldar Sayranov"))
