# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AboutWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AboutWidget(object):
    def setupUi(self, AboutWidget):
        AboutWidget.setObjectName("AboutWidget")
        AboutWidget.resize(430, 328)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../icons/info_black.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        AboutWidget.setWindowIcon(icon)
        self.logo = QtWidgets.QLabel(AboutWidget)
        self.logo.setGeometry(QtCore.QRect(20, 20, 100, 100))
        self.logo.setPixmap(QtGui.QPixmap("../icons/logo.svg"))
        self.logo.setScaledContents(True)
        self.logo.setObjectName("logo")
        self.label_2 = QtWidgets.QLabel(AboutWidget)
        self.label_2.setGeometry(QtCore.QRect(140, 30, 121, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(AboutWidget)
        self.label_3.setGeometry(QtCore.QRect(140, 90, 211, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(AboutWidget)
        self.label_4.setGeometry(QtCore.QRect(140, 70, 91, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(AboutWidget)
        self.label_5.setGeometry(QtCore.QRect(30, 150, 71, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(AboutWidget)
        self.label_6.setGeometry(QtCore.QRect(30, 190, 71, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(AboutWidget)
        self.label_7.setGeometry(QtCore.QRect(120, 190, 55, 16))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(AboutWidget)
        self.label_8.setGeometry(QtCore.QRect(120, 210, 55, 16))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(AboutWidget)
        self.label_9.setGeometry(QtCore.QRect(120, 230, 55, 16))
        self.label_9.setObjectName("label_9")
        self.github_button = QtWidgets.QPushButton(AboutWidget)
        self.github_button.setGeometry(QtCore.QRect(20, 280, 391, 28))
        self.github_button.setObjectName("github_button")

        self.retranslateUi(AboutWidget)
        QtCore.QMetaObject.connectSlotsByName(AboutWidget)

    def retranslateUi(self, AboutWidget):
        _translate = QtCore.QCoreApplication.translate
        AboutWidget.setWindowTitle(_translate("AboutWidget", "About"))
        self.label_2.setText(_translate("AboutWidget", "Shuffle"))
        self.label_3.setText(_translate("AboutWidget", "Copyright (c) 2022 Renat Skosarev"))
        self.label_4.setText(_translate("AboutWidget", "Audio Player"))
        self.label_5.setText(_translate("AboutWidget", "Version:"))
        self.label_6.setText(_translate("AboutWidget", "Libraries:"))
        self.label_7.setText(_translate("AboutWidget", "• PyQt5"))
        self.label_8.setText(_translate("AboutWidget", "• Pillow"))
        self.label_9.setText(_translate("AboutWidget", "• tinytag"))
        self.github_button.setText(_translate("AboutWidget", "GitHub"))
